quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.http.port=8081
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/tech_store?options=-c%20TimeZone=UTC
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.jdbc.additional-jdbc-properties.stringtype=unspecified

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=tech-store
smallrye.jwt.sign.key.location=privateKey.pem